Update stuff idk

diff --git a/build/scripts/Flames b/build/scripts/Flames
--- a/build/scripts/Flames
+++ b/build/scripts/Flames
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# Copyright © 2015-2021 the original authors.
+# Copyright Â© 2015-2021 the original authors.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -32,10 +32,10 @@
 #       Busybox and similar reduced shells will NOT work, because this script
 #       requires all of these POSIX shell features:
 #         * functions;
-#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
-#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
-#         * compound commands having a testable exit status, especially «case»;
-#         * various built-in commands including «command», «set», and «ulimit».
+#         * expansions Â«$varÂ», Â«${var}Â», Â«${var:-default}Â», Â«${var+SET}Â»,
+#           Â«${var#prefix}Â», Â«${var%suffix}Â», and Â«$( cmd )Â»;
+#         * compound commands having a testable exit status, especially Â«caseÂ»;
+#         * various built-in commands including Â«commandÂ», Â«setÂ», and Â«ulimitÂ».
 #
 #   Important for patching:
 #
@@ -55,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -80,13 +80,11 @@ do
     esac
 done
 
-APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
-
-APP_NAME="Flames"
+# This is normally unused
+# shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-
-# Add default JVM options here. You can also use JAVA_OPTS and FLAMES_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME=$( cd "${APP_HOME:-./}.." > /dev/null && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +112,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/Flames-7.0.1.jar:$APP_HOME/lib/JDA-5.0.0-beta.3.jar:$APP_HOME/lib/google-cloud-dialogflow-4.5.0.jar:$APP_HOME/lib/google-cloud-language-2.1.6.jar:$APP_HOME/lib/bugsnag-3.6.2.jar:$APP_HOME/lib/protobuf-java-3.19.3.jar:$APP_HOME/lib/protobuf-java-util-3.19.3.jar:$APP_HOME/lib/proto-google-cloud-dialogflow-v2-4.5.0.jar:$APP_HOME/lib/proto-google-cloud-dialogflow-v2beta1-0.103.0.jar:$APP_HOME/lib/auto-value-annotations-1.9.jar:$APP_HOME/lib/proto-google-cloud-language-v1-2.1.6.jar:$APP_HOME/lib/proto-google-cloud-language-v1beta2-0.88.6.jar:$APP_HOME/lib/google-auth-library-credentials-1.4.0.jar:$APP_HOME/lib/google-auth-library-oauth2-http-1.4.0.jar:$APP_HOME/lib/guava-31.0.1-jre.jar:$APP_HOME/lib/google-http-client-1.41.2.jar:$APP_HOME/lib/google-http-client-gson-1.41.2.jar:$APP_HOME/lib/grpc-alts-1.44.0.jar:$APP_HOME/lib/grpc-api-1.44.0.jar:$APP_HOME/lib/grpc-auth-1.44.0.jar:$APP_HOME/lib/grpc-context-1.44.0.jar:$APP_HOME/lib/grpc-core-1.44.0.jar:$APP_HOME/lib/grpc-grpclb-1.44.0.jar:$APP_HOME/lib/grpc-netty-shaded-1.44.0.jar:$APP_HOME/lib/grpc-protobuf-1.44.0.jar:$APP_HOME/lib/grpc-protobuf-lite-1.44.0.jar:$APP_HOME/lib/grpc-services-1.44.0.jar:$APP_HOME/lib/grpc-stub-1.44.0.jar:$APP_HOME/lib/api-common-2.1.3.jar:$APP_HOME/lib/gax-2.11.0.jar:$APP_HOME/lib/gax-grpc-2.11.0.jar:$APP_HOME/lib/proto-google-common-protos-2.7.2.jar:$APP_HOME/lib/trove4j-3.0.3.jar:$APP_HOME/lib/jackson-annotations-2.14.1.jar:$APP_HOME/lib/jackson-databind-2.14.1.jar:$APP_HOME/lib/jackson-core-2.14.1.jar:$APP_HOME/lib/slf4j-api-1.7.36.jar:$APP_HOME/lib/nv-websocket-client-2.14.jar:$APP_HOME/lib/okhttp-4.10.0.jar:$APP_HOME/lib/opus-java-1.1.1.jar:$APP_HOME/lib/commons-collections4-4.4.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/javax.annotation-api-1.3.2.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/checker-qual-3.21.1.jar:$APP_HOME/lib/error_prone_annotations-2.11.0.jar:$APP_HOME/lib/j2objc-annotations-1.3.jar:$APP_HOME/lib/httpclient-4.5.13.jar:$APP_HOME/lib/commons-logging-1.2.jar:$APP_HOME/lib/commons-codec-1.15.jar:$APP_HOME/lib/httpcore-4.4.15.jar:$APP_HOME/lib/opencensus-contrib-http-util-0.31.0.jar:$APP_HOME/lib/opencensus-api-0.31.0.jar:$APP_HOME/lib/conscrypt-openjdk-uber-2.5.1.jar:$APP_HOME/lib/perfmark-api-0.23.0.jar:$APP_HOME/lib/annotations-4.1.1.4.jar:$APP_HOME/lib/animal-sniffer-annotations-1.20.jar:$APP_HOME/lib/grpc-xds-1.44.0.jar:$APP_HOME/lib/gson-2.8.9.jar:$APP_HOME/lib/re2j-1.5.jar:$APP_HOME/lib/bcpkix-jdk15on-1.67.jar:$APP_HOME/lib/bcprov-jdk15on-1.67.jar:$APP_HOME/lib/opencensus-proto-0.2.0.jar:$APP_HOME/lib/threetenbp-1.5.2.jar:$APP_HOME/lib/okio-jvm-3.0.0.jar:$APP_HOME/lib/kotlin-stdlib-jdk8-1.5.31.jar:$APP_HOME/lib/kotlin-stdlib-jdk7-1.5.31.jar:$APP_HOME/lib/kotlin-stdlib-1.6.20.jar:$APP_HOME/lib/opus-java-api-1.1.1.jar:$APP_HOME/lib/opus-java-natives-1.1.1.jar:$APP_HOME/lib/kotlin-stdlib-common-1.6.20.jar:$APP_HOME/lib/annotations-13.0.jar:$APP_HOME/lib/jna-4.4.0.jar
+CLASSPATH=$APP_HOME/lib/Flames-7.1.jar:$APP_HOME/lib/JDA-5.0.0-beta.3.jar:$APP_HOME/lib/google-cloud-dialogflow-4.5.0.jar:$APP_HOME/lib/google-cloud-language-2.1.6.jar:$APP_HOME/lib/bugsnag-3.6.2.jar:$APP_HOME/lib/protobuf-java-3.19.3.jar:$APP_HOME/lib/protobuf-java-util-3.19.3.jar:$APP_HOME/lib/proto-google-cloud-dialogflow-v2-4.5.0.jar:$APP_HOME/lib/proto-google-cloud-dialogflow-v2beta1-0.103.0.jar:$APP_HOME/lib/auto-value-annotations-1.9.jar:$APP_HOME/lib/proto-google-cloud-language-v1-2.1.6.jar:$APP_HOME/lib/proto-google-cloud-language-v1beta2-0.88.6.jar:$APP_HOME/lib/google-auth-library-credentials-1.4.0.jar:$APP_HOME/lib/google-auth-library-oauth2-http-1.4.0.jar:$APP_HOME/lib/guava-31.0.1-jre.jar:$APP_HOME/lib/google-http-client-1.41.2.jar:$APP_HOME/lib/google-http-client-gson-1.41.2.jar:$APP_HOME/lib/grpc-alts-1.44.0.jar:$APP_HOME/lib/grpc-api-1.44.0.jar:$APP_HOME/lib/grpc-auth-1.44.0.jar:$APP_HOME/lib/grpc-context-1.44.0.jar:$APP_HOME/lib/grpc-core-1.44.0.jar:$APP_HOME/lib/grpc-grpclb-1.44.0.jar:$APP_HOME/lib/grpc-netty-shaded-1.44.0.jar:$APP_HOME/lib/grpc-protobuf-1.44.0.jar:$APP_HOME/lib/grpc-protobuf-lite-1.44.0.jar:$APP_HOME/lib/grpc-services-1.44.0.jar:$APP_HOME/lib/grpc-stub-1.44.0.jar:$APP_HOME/lib/api-common-2.1.3.jar:$APP_HOME/lib/gax-2.11.0.jar:$APP_HOME/lib/gax-grpc-2.11.0.jar:$APP_HOME/lib/proto-google-common-protos-2.7.2.jar:$APP_HOME/lib/trove4j-3.0.3.jar:$APP_HOME/lib/jackson-annotations-2.14.1.jar:$APP_HOME/lib/jackson-databind-2.14.1.jar:$APP_HOME/lib/jackson-core-2.14.1.jar:$APP_HOME/lib/slf4j-api-1.7.36.jar:$APP_HOME/lib/nv-websocket-client-2.14.jar:$APP_HOME/lib/okhttp-4.10.0.jar:$APP_HOME/lib/opus-java-1.1.1.jar:$APP_HOME/lib/commons-collections4-4.4.jar:$APP_HOME/lib/jsr305-3.0.2.jar:$APP_HOME/lib/javax.annotation-api-1.3.2.jar:$APP_HOME/lib/failureaccess-1.0.1.jar:$APP_HOME/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:$APP_HOME/lib/checker-qual-3.21.1.jar:$APP_HOME/lib/error_prone_annotations-2.11.0.jar:$APP_HOME/lib/j2objc-annotations-1.3.jar:$APP_HOME/lib/httpclient-4.5.13.jar:$APP_HOME/lib/commons-logging-1.2.jar:$APP_HOME/lib/commons-codec-1.15.jar:$APP_HOME/lib/httpcore-4.4.15.jar:$APP_HOME/lib/opencensus-contrib-http-util-0.31.0.jar:$APP_HOME/lib/opencensus-api-0.31.0.jar:$APP_HOME/lib/conscrypt-openjdk-uber-2.5.1.jar:$APP_HOME/lib/perfmark-api-0.23.0.jar:$APP_HOME/lib/annotations-4.1.1.4.jar:$APP_HOME/lib/animal-sniffer-annotations-1.20.jar:$APP_HOME/lib/grpc-xds-1.44.0.jar:$APP_HOME/lib/gson-2.8.9.jar:$APP_HOME/lib/re2j-1.5.jar:$APP_HOME/lib/bcpkix-jdk15on-1.67.jar:$APP_HOME/lib/bcprov-jdk15on-1.67.jar:$APP_HOME/lib/opencensus-proto-0.2.0.jar:$APP_HOME/lib/threetenbp-1.5.2.jar:$APP_HOME/lib/okio-jvm-3.0.0.jar:$APP_HOME/lib/kotlin-stdlib-jdk8-1.5.31.jar:$APP_HOME/lib/kotlin-stdlib-jdk7-1.5.31.jar:$APP_HOME/lib/kotlin-stdlib-1.6.20.jar:$APP_HOME/lib/opus-java-api-1.1.1.jar:$APP_HOME/lib/opus-java-natives-1.1.1.jar:$APP_HOME/lib/kotlin-stdlib-common-1.6.20.jar:$APP_HOME/lib/annotations-13.0.jar:$APP_HOME/lib/jna-4.4.0.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,22 +131,29 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
 if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
     case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -193,16 +198,26 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
-# Collect all arguments for the java command;
-#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $FLAMES_OPTS can contain fragments of
-#     shell script including quotes and variable substitutions, so put them in
-#     double quotes to make sure that they get re-expanded; and
-#   * put everything else in single quotes, so that it's not re-expanded.
+
+# Add default JVM options here. You can also use JAVA_OPTS and FLAMES_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
+
+# Collect all arguments for the java command:
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
+#     and any embedded shellness will be escaped.
+#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
+#     treated as '${Hostname}' itself on the command line.
 
 set -- \
         -classpath "$CLASSPATH" \
         com.severalcircles.flames.Flames \
         "$@"
+
+# Stop when "xargs" is not available.
+if ! command -v xargs >/dev/null 2>&1
+then
+    die "xargs is not available"
+fi
 
 # Use "xargs" to parse quoted args.
 #
